name: Build and Release sys-patch

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        path: sys-patch
        submodules: recursive

    - name: Extract version
      id: version
      run: |
        VERSION=$(grep 'export VERSION := ' sys-patch/Makefile | awk -F' := ' '{print $2}' | tr -d '[:space:]')
        echo "TAG_NAME=${VERSION}" >> $GITHUB_ENV
        echo "RELEASE_NAME=sys-patch v${VERSION}" >> $GITHUB_ENV

    - name: Build
      run: make -C sys-patch -j$(nproc) dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_NAME }}
        path: sys-patch/out/
        retention-days: 7

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_NAME }}
        body: "Automated release for sys-patch v${{ env.TAG_NAME }}"
        files: sys-patch/sys-patch.zip
        draft: false
        prerelease: false
        generate_release_notes: true
